driver = mysql
connect = host=127.0.0.1 dbname=mail user=mail_admin password=$SERVER_ADMIN_PASSWORD
default_pass_scheme = PLAIN-MD5
password_query = SELECT email as user, password FROM users WHERE email='%u';