sudo apt-get update
sudo apt-get dist-upgrade -y
sudo apt-get install curl -y
sudo apt-get install git -y
sudo apt-get install openssh-server -y
sudo apt-get install lamp-server^ -y
sudo apt-get install phpmyadmin -y
sudo apt-get install ghostscript -y
sudo apt-get install libapache2-mod-php -y
sudo apt-get install php-bcmath -y
sudo apt-get install php-curl -y
sudo apt-get install php-imagick -y
sudo apt-get install php-intl -y
sudo apt-get install php-json -y
sudo apt-get install php-mbstring -y
sudo apt-get install php-mysql -y
sudo apt-get install php-xml -y
sudo apt-get install php-zip -y
sudo apt-get install python3-pip -y
sudo apt-get install python3-mysql.connector
sudo apt-get install bind9 -y
sudo apt-get install bind9utils -y 
sudo apt-get install bind9-doc -y
sudo apt-get install certbot -y
sudo apt-get install python3-certbot-apache -y
sudo apt-get install postfix -y
sudo apt-get install postfix-mysql -y
sudo apt-get install postfix-doc -y
sudo apt-get install dovecot-common -y
sudo apt-get install dovecot-imapd -y
sudo apt-get install dovecot-pop3d -y
sudo apt-get install libsasl2-2 -y
sudo apt-get install libsasl2-modules -y
sudo apt-get install libsasl2-modules-sql -y
sudo apt-get install sasl2-bin -y
sudo apt-get install libpam-mysql -y
sudo apt-get install mailutils -y
sudo apt-get install dovecot-mysql -y
sudo apt-get install dovecot-sieve -y
sudo apt-get install dovecot-managesieved -y
