; BIND reverse data file for empty rfc1918 zone
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
$TTL	86400
@	IN	SOA	ns1.$SERVER_DOMAIN_NAME. root.localhost. (
			      2		; Serial
			 604800		; Refresh
			  86400		; Retry
			2419200		; Expire
			  86400 )	; Negative Cache TTL
;
@	IN	NS	ns1.$SERVER_DOMAIN_NAME.
;@	IN	NS	ns2.$SERVER_DOMAIN_NAME.
ns1	IN	A	$SERVER_IP_ADDRESS
@ 	IN	MX 10 	mail.$SERVER_DOMAIN_NAME.
$SERVER_DOMAIN_NAME.	IN	A	$SERVER_IP_ADDRESS
www	IN	A	$SERVER_IP_ADDRESS
mail	IN	A	$SERVER_IP_ADDRESS
$SERVER_DOMAIN_NAME.    IN      TXT     "v=spf1 +a +ip4:$SERVER_IP_ADDRESS ~all"

mail._domainkey	IN	TXT	( "v=DKIM1; h=sha256; k=rsa;"
	  "p=$PART0"
	  "$PART1"
	  "$PART2"
	);

_dmarc             IN    TXT    "v=DMARC1; p=reject; rua=mailto:webmaster@$SERVER_DOMAIN_NAME; pct=100; adkim=s; aspf=s;"
