# Log to syslog
Syslog                  yes
# Required to use local socket with Postfix chroot
UMask                   002

# Sign for example.com with key default (We overrule this with the tables below)
# (Comment out Domain, KeyFile, and Selector if they are active)
# Domain                example.com
# KeyFile               /etc/opendkim/keys/default.private
# Selector              default

# Canonicalization: Relaxed/Simple is the most compatible standard
Canonicalization        relaxed/simple

# Mode: s = signer, v = verifier
Mode                    sv

# Socket: Use a local TCP port to talk to Postfix
Socket                  inet:12301@localhost

# Map Files (We will create these next)
KeyTable                refile:/etc/opendkim/KeyTable
SigningTable            refile:/etc/opendkim/SigningTable
ExternalIgnoreList      refile:/etc/opendkim/TrustedHosts
InternalHosts           refile:/etc/opendkim/TrustedHosts